start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Create_New_Tarstav.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateADDRESS.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateALIMENTY.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateAppendix.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateAppointment.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateBANK.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateCatalogs.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateCatalogsup.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateCatpodr.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateCatStr.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateCONSCRIPTION.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateContact.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateDEBTS.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateDoplata.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateEDUCATION.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateINN.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateInvalid.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateISPLIST.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateKLNDR_1.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateKLNDR_2.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateNDFL.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreatePassport.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreatePerson.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreatePOST.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateRelative.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateSHTRAF.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateSNILS.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateSTAFFSTRUCT.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateSUMOPL.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateTabel.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateTARSTAV.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateTarstavsync.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateVacations.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateVredn.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe CreateKPS.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log