start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_ADDRESS.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_APPOINTMENT.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_Catalogs.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_Catpodr.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_CatStr.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_CONSCRIPTION.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_CONTACT.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_EDUCATION.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_INN.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_PASSPORT.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_PERSON.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_Post.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_RELATIVE.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_SNILS.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_STAFFSTRUCT.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_TARSTAV.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_EM_VACATIONS.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_NEWTARSTAV.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log