start /w \\dep968-galsrv3\GalSrv\exe\asql.exe ExportKatPodrToBackup.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe ExportCatalogsToBackup.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Catalogs.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Katpodr.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Kathist.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe ExportTarStavToBackup.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe ExportStaffStructToBackup.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Tarstav.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Klrejim.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_StaffStruct.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Update_Staffstruct_Num.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Post.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Persons.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Lschet.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Appointments.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Vacantionsts.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Vacations.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_SNILS.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Relative.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Passport.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_INN.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Education.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Conscription.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Import_Gal_Communications.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Update_Persons.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log
start /w \\dep968-galsrv3\GalSrv\exe\asql.exe Update_Lschet.lot /c:asql.cfg /L+ /NUSK- /j+ /jr+ /jf:journal.log